project:
  type: website

title: "Nathan Callaway â€“ Bioinformatics Portfolio"
author: "Nathan Callaway"

format:
  html:
    theme: cosmo

website:
  navbar:
    right:
      - text: "Projects"
        href: projects.qmd
